config/routes.rb
require 'sidekiq/web'

GameSocial::Application.routes.draw do
  match 'teams/:id/invite', to: 'teams#invite', as: 'invite_team', via: [:get]
  match 'teams/:id/invite', to: 'teams#send_invite', as: 'send_invite_team', via: [:post]
  match 'teams/new_for_tournament/:tournament_id', to: 'teams#new_for_tournament', as: 'new_team_for_tournament', via: [:get] 
  match 'teams/:id/join', to: 'teams#join', as: 'join_team', via: [:get]
  match 'teams/:id/leave', to: 'teams#leave', as: 'leave_team', via: [:get]
  resources :teams
  match 'tournaments/:id/rounds/:bracket_id/concede', to: 'tournaments#concede', as: 'concede_tournament_round', via: [:get] 
  match 'tournaments/:id/rounds/:bracket_id/resolve', to: 'tournaments#resolve', as: 'resolve_tournament_round', via: [:post] 
  match 'tournaments/:id/lock', to: 'tournaments#lock', as: 'lock_tournament', via: [:get] 
  match 'tournaments/new_for_event/:event_id', to: 'tournaments#new_for_event', as: 'new_tournament_for_event', via: [:get] 
  resources :tournaments

  match 'playlists/:id', to: 'playlists#add_game', as: 'add_game', via: [:post]
  match 'playlists/:id/:game_id', to: 'playlists#delete_game', as: 'delete_game', via: [:delete]
  resources :playlists

  match 'groups/:id/join', to: 'groups#join', as: 'join_group', via: [:get]
  match 'groups/:id/join/:user_id', to: 'groups#join', as: 'join_user_group', via: [:get]
  match 'groups/:id/leave', to: 'groups#leave', as: 'leave_group', via: [:get]
  match 'groups/:id/leave/:user_id', to: 'groups#leave', as: 'leave_user_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#invite', as: 'invite_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#send_invite', as: 'send_invite_group', via: [:post]
  resources :groups

  resources :posts

  match 'game_events/new_for_event/:event_id', to: 'game_events#new_for_event', as: 'new_game_event_for_event', via: [:get] 
  match 'posts/new_for_event/:event_id', to: 'posts#new_for_event', as: 'new_post_for_event', via: [:get] 
  match 'posts/new_for_game_event/:game_event_id', to: 'posts#new_for_game_event', as: 'new_post_for_game_event', via: [:get] 
  match 'game_events/:id/join', to: 'game_events#join', as: 'join_game_event', via: [:get]
  match 'game_events/:id/join/:user_id', to: 'game_events#join', as: 'join_user_game_event', via: [:get]
  match 'game_events/:id/leave', to: 'game_events#leave', as: 'leave_game_event', via: [:get]
  match 'game_events/:id/leave/:user_id', to: 'game_events#leave', as: 'leave_user_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#invite', as: 'invite_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#send_invite', as: 'send_invite_game_event', via: [:post]
  resources :game_events

  match 'events/:id/game_social_servers', to: 'events#game_social_servers', as: 'events_game_social_servers', via: [:post]
  match 'events/:id/game_social_servers/:game_social_server_id', to: 'events#delete_game_social_server', as: 'delete_events_game_social_server', via: [:delete]
  match 'events/:id/join', to: 'events#join', as: 'join_event', via: [:get]
  match 'events/:id/join/:user_id', to: 'events#join', as: 'join_user_event', via: [:get]
  match 'events/:id/leave', to: 'events#leave', as: 'leave_event', via: [:get]
  match 'events/:id/leave/:user_id', to: 'events#leave', as: 'leave_user_event', via: [:get]
  match 'events/:id/invite', to: 'events#invite', as: 'invite_event', via: [:get]
  match 'events/:id/invite', to: 'events#send_invite', as: 'send_invite_event', via: [:post]
  resources :events

  resources :alerts

  resources :alert_conditions

  resources :alert_schedules

  resources :game_locations

  resources :friendships

  match 'game_social_servers/new_source', to: 'game_social_servers#new_source', as: 'new_source_game_social_server', via: [:get]
  resources :game_social_servers

  resources :chat_servers

  match 'users/sync', to: 'users#sync', as: 'sync_users', via:[:get]
  match 'users/sync_location', to: 'users#sync_location', as: 'sync_users_location', via:[:get]
  match 'users/:id/games', to: 'users#add_game', as: 'user_game', via: [:post]
  resources :users do
    get :autocomplete_user_name, :on => :collection
  end
  resources :users

  resources :games
  root to: 'users#home'
  match 'auth/steam/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/developer/callback', to: 'sessions#create', via: [:get, :post]
 
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end unless Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  delegate :name, :to => :user, :prefix => true, :allow_nil => true
  has_one :object_permission, as: :permissible_object
  accepts_nested_attributes_for :object_permission
  delegate :is_visible_to?, :to => :object_permission

  validates :name, :description, :presence => true  

  has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :leave, :invite, :send_invite]

  before_filter :enforce_admin, :only => [:index]

  # GET /groups
  # GET /groups.json
  def index
    @groups_grid = initialize_grid(all_visible(Group), :include => [:user])

  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @invite = Invite.new
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.object_permission = ObjectPermission.new
  end

  # GET /groups/1/edit
  def edit
  end

  # GET /groups/1/invite
  def invite
    @invite = Invite.new
  end

  # POST /groups/1/invite
  def send_invite
    @invite = Invite.new(invite_params)
    @invite.group = @group
    @invite.user =  current_user
    @invite.deliver
    redirect_to group_path(@group), notice: "Invite sent"
  end

  # GET /events/1/join
  def join
    user = User.find_by_id(params[:user_id]) || current_user
    validate_ownership(user)
    user.join_group(@group)
    redirect_to groups_path, notice: 'Group joined.' 
  end

  # GET /events/1/leave
  def leave
    user = User.find_by_id(params[:user_id]) || current_user
    validate_ownership(user)
    user.leave_event(@group)
    redirect_to groups_path, notice: 'Group left.' 
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user unless @group.user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    enforce_ownership(@group)
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    enforce_ownership(@group)
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, 
                                    :description, 
                                    :user_id,
                                    object_permission_attributes: [:permission_type])
    end

    def invite_params
      params.require(:invite).permit(:email)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => { role: "form-horizontal"}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
  <%= f.fields_for :object_permission do |builder| %>
    <% render 'object_permissions/form', :builder => builder %>
  <% end %>
  </div>
  <% if is_admin? %>
   <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id, User.all, :id, :name,  {:selected => (@group.user_id || current_user.id)}, 
          {:class => "form-control"} %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path, :class => "btn btn-warning" %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<%= grid(@groups_grid) do |g|

  g.blank_slate  do
    content_tag :div, "No Groups found", class: 'well'
  end

  g.row_attributes do |object|
    { onclick: "maybeVisit(event, '#{url_for(object)}');" }
  end

  g.column name: 'Name', attribute: 'name' do |group|
    group.name
  end

  g.column name: 'Description', attribute: 'description' do |group|
    group.description
  end
  
  g.column name: 'Owner', model: User, attribute: 'name' do |group|
    group.user_name
  end

  g.column do |group|
    if current_user && current_user.in_group?(group)
      link_to 'Leave', leave_group_path(group), :class => "btn btn-warning"
    else
      link_to 'Join', join_group_path(group), :class => "btn btn-success"
    end
  end

  g.column do |group|
    if current_user.owns(group)
      link_to 'Edit', edit_group_path(group), :class => "btn btn-primary" 
    end
  end

  g.column do |group|
    if current_user.owns(group)
      link_to 'Destroy', group, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }
    end
  end
end -%>

<%= link_to 'New Group', new_group_path, :class => "btn btn-success" %>

app/views/groups/invite.html.erb
<h1>Send Invite</h1>

<%= render 'invite_form', :type => "Group", :url => invite_group_path(@group) %>

<%= link_to 'Back', group_path(@group) %>

app/views/groups/new.html.erb
<h1>Create a Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path, :class => "btn btn-warning" %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-condensed">
  <tr>
    <td><h5 class="text-center">Name</h5></td>
    <td><p class="text-center"><%= @group.name %></p></td>
  </tr>
  <tr>
    <td><h5 class="text-center">Description</h5></td>
    <td><p class="text-center"><%= @group.description %></p></td>
  </tr>
  <tr>
    <td><h5 class="text-center">Owner</h5></td>
    <td><p class="text-center"><%= @group.user_name %></p></td>
  </tr>
  <tr>
    <td><h5 class="text-center">Join Group</h5></td>
    <td><p class="text-center">
    <% if current_user.in_group?(@group) %>
      <%= link_to 'Leave', leave_group_path(@group), :class => "btn btn-warning" %>
    <% else %>
      <%= link_to 'Join', join_group_path(@group), :class => "btn btn-primary" %>
    <% end %>
  </p></td>
  </tr>
  </tr>
  <tr>
    <td><h5 class="text-center">Invite to Group</h5></td>
    <td><p class="text-center"><a data-toggle="modal" href="#inviteModal" class="btn btn-primary">Invite</a></p></td>
  </tr>
</table>

<h2>Members</h2>
<div class="row">
  <% for i in 0..5 %>
    <div class="col-lg-2 col-md-2">
      <%  @group.users.each_with_index do |u, index| %>
        <% if index % 6 == i %>
          <%= render "users/user", :u => u %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<%= render '/events/invite_form', :type => "Group", :url => invite_group_path(@group) %>

<% if current_user.owns(@group) %>
  <%= link_to 'Edit', edit_group_path(@group), :class => "btn btn-primary" %> |
<% end %>
<%= link_to 'Back', groups_path, :class => "btn btn-warning"  %>