config/routes.rb
require 'sidekiq/web'

GameSocial::Application.routes.draw do
  match 'teams/:id/invite', to: 'teams#invite', as: 'invite_team', via: [:get]
  match 'teams/:id/invite', to: 'teams#send_invite', as: 'send_invite_team', via: [:post]
  match 'teams/new_for_tournament/:tournament_id', to: 'teams#new_for_tournament', as: 'new_team_for_tournament', via: [:get] 
  match 'teams/:id/join', to: 'teams#join', as: 'join_team', via: [:get]
  match 'teams/:id/leave', to: 'teams#leave', as: 'leave_team', via: [:get]
  resources :teams
  match 'tournaments/:id/rounds/:bracket_id/concede', to: 'tournaments#concede', as: 'concede_tournament_round', via: [:get] 
  match 'tournaments/:id/rounds/:bracket_id/resolve', to: 'tournaments#resolve', as: 'resolve_tournament_round', via: [:post] 
  match 'tournaments/:id/lock', to: 'tournaments#lock', as: 'lock_tournament', via: [:get] 
  match 'tournaments/new_for_event/:event_id', to: 'tournaments#new_for_event', as: 'new_tournament_for_event', via: [:get] 
  resources :tournaments

  match 'playlists/:id', to: 'playlists#add_game', as: 'add_game', via: [:post]
  match 'playlists/:id/:game_id', to: 'playlists#delete_game', as: 'delete_game', via: [:delete]
  resources :playlists

  match 'groups/:id/join', to: 'groups#join', as: 'join_group', via: [:get]
  match 'groups/:id/join/:user_id', to: 'groups#join', as: 'join_user_group', via: [:get]
  match 'groups/:id/leave', to: 'groups#leave', as: 'leave_group', via: [:get]
  match 'groups/:id/leave/:user_id', to: 'groups#leave', as: 'leave_user_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#invite', as: 'invite_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#send_invite', as: 'send_invite_group', via: [:post]
  resources :groups

  resources :posts

  match 'game_events/new_for_event/:event_id', to: 'game_events#new_for_event', as: 'new_game_event_for_event', via: [:get] 
  match 'posts/new_for_event/:event_id', to: 'posts#new_for_event', as: 'new_post_for_event', via: [:get] 
  match 'posts/new_for_game_event/:game_event_id', to: 'posts#new_for_game_event', as: 'new_post_for_game_event', via: [:get] 
  match 'game_events/:id/join', to: 'game_events#join', as: 'join_game_event', via: [:get]
  match 'game_events/:id/join/:user_id', to: 'game_events#join', as: 'join_user_game_event', via: [:get]
  match 'game_events/:id/leave', to: 'game_events#leave', as: 'leave_game_event', via: [:get]
  match 'game_events/:id/leave/:user_id', to: 'game_events#leave', as: 'leave_user_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#invite', as: 'invite_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#send_invite', as: 'send_invite_game_event', via: [:post]
  resources :game_events

  match 'events/:id/game_social_servers', to: 'events#game_social_servers', as: 'events_game_social_servers', via: [:post]
  match 'events/:id/game_social_servers/:game_social_server_id', to: 'events#delete_game_social_server', as: 'delete_events_game_social_server', via: [:delete]
  match 'events/:id/join', to: 'events#join', as: 'join_event', via: [:get]
  match 'events/:id/join/:user_id', to: 'events#join', as: 'join_user_event', via: [:get]
  match 'events/:id/leave', to: 'events#leave', as: 'leave_event', via: [:get]
  match 'events/:id/leave/:user_id', to: 'events#leave', as: 'leave_user_event', via: [:get]
  match 'events/:id/invite', to: 'events#invite', as: 'invite_event', via: [:get]
  match 'events/:id/invite', to: 'events#send_invite', as: 'send_invite_event', via: [:post]
  resources :events

  resources :alerts

  resources :alert_conditions

  resources :alert_schedules

  resources :game_locations

  resources :friendships

  match 'game_social_servers/new_source', to: 'game_social_servers#new_source', as: 'new_source_game_social_server', via: [:get]
  resources :game_social_servers

  resources :chat_servers

  match 'users/sync', to: 'users#sync', as: 'sync_users', via:[:get]
  match 'users/sync_location', to: 'users#sync_location', as: 'sync_users_location', via:[:get]
  match 'users/:id/games', to: 'users#add_game', as: 'user_game', via: [:post]
  resources :users do
    get :autocomplete_user_name, :on => :collection
  end
  resources :users

  resources :games
  root to: 'users#home'
  match 'auth/steam/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/developer/callback', to: 'sessions#create', via: [:get, :post]
 
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end unless Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
end

app/models/event.rb
require 'calendar'
require 'workers/notification_worker'

class Event < ActiveRecord::Base
  belongs_to :user
  delegate :name, :to => :user, :prefix => true, :allow_nil => true
  delegate :email, :to => :user, :prefix => true, :allow_nil => true
  has_many :posts, as: :postable
  has_many :playlists
  has_many :game_events, ->{ order(:game_start_time) }, :dependent => :destroy
  has_many :tournaments, :dependent => :destroy
  has_and_belongs_to_many :game_social_servers
  has_one :object_permission, as: :permissible_object
  delegate :is_visible_to?, :to => :object_permission
  has_and_belongs_to_many :users

  accepts_nested_attributes_for :object_permission

  before_save :set_defaults
  before_destroy :delete_event

  after_commit :export_event, :on => [:create, :update]

  default_scope { order(start_time: :asc) }

  validate :valid_length?
  validates :name, :presence => true

  def valid_length?
    if start_time >= end_time
      errors.add(:end_time, 'must occur after start_time')
    end
  end

  def export_event
    if calendar.event
      calendar.update_event
    else
      calendar.create_event
    end
  end

  def delete_event
    calendar.delete_event
  end

  def next_event
    next_ge = game_events.where("game_start_time > ?", DateTime.now).first
    next_t = tournaments.where("tournament_start_time > ?", DateTime.now).first
    return next_ge unless next_t
    return next_t unless next_ge
    return (next_t.start_time < next_ge.start_time) ? next_t : next_ge
  end

  def set_defaults
    self.start_time ||= DateTime.now.beginning_of_minute
    self.end_time ||= DateTime.now.beginning_of_minute
  end

  def formatted_start_time
    start_time.to_formatted_s(:long_ordinal) if start_time
  end

  def formatted_end_time
    end_time.to_formatted_s(:long_ordinal) if end_time
  end

  def popular_games
    popularity = {}
    game_events.each do |ge|
      popularity[ge.game] = [] unless popularity[ge.game]
      popularity[ge.game].concat(ge.users.to_a)
    end

    playlists.each do |p|
      p.games.each do |g|
        popularity[g] = [] unless popularity[g]
        popularity[g].append(p.user)
      end
    end

    games = []
    popularity.each {|k,v| games.append({ game: k, users: v.sort.uniq}) if v.size > 0}
    games.sort_by {|g| -g[:users].size }
  end

  def calendar
    @calendar ||= Calendar.new(self)
  end

  def notify
    users.each {|u| Workers::NotificationWorker.perform_async(u.id, notification_title) }
  end

  def notification_title
    "Lan Party #{name} was updated."
  end
end

app/controllers/events_controller.rb
require 'ical'

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :join, :leave, :invite, :send_invite, :game_social_servers, :delete_game_social_server]
  before_filter :spoof_login, only: [:show, :index]
  before_filter :enforce_login, except: [:index, :show]
  
  # GET /events
  # GET /events.json
  def index
    @events = all_visible(Event)
    @events_grid = initialize_grid(@events,
                                   :include => [:user])
    respond_to do |format|
      format.html {}
      format.ics do
        expires_now
        render inline: Ical.ical_from_collection(@events).to_s
      end 
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    enforce_visibility(@event)
    @invite = Invite.new
    @post = Post.new({ :postable => @event })
    @posts_grid  = initialize_grid(@event.posts, :include => [:user])
    @game_events = all_visible(GameEvent).where("event_id = ?", @event.id)
    @game_servers_grid  = initialize_grid(@event.game_social_servers, :include => [:game])
    @tournaments = all_visible(Tournament).where("event_id = ?", @event.id)
    @filter = params["filter"]
    if @filter == "owned" && current_user
      @game_events = @game_events.where("game_id in (?)", current_user.games.map {|g| g.id })
    end
    @filter_tournaments = params["filter_tournaments"]
    if @filter_tournaments == "owned" && current_user
      @tournaments = @tournaments.where("game_id in (?)", current_user.games.map {|g| g.id })
    end
    
    @game_events_grid = initialize_grid(@game_events, :include => [:game])
    @tournaments_grid = initialize_grid(@tournaments, :include => [:game])
    respond_to do |format|
      format.html {}
      format.ics do
        expires_now
        render inline: Ical.ical_from_collection(@game_events).to_s
      end 
    end
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.object_permission = ObjectPermission.new
    @event.start_time = DateTime.now
    @event.end_time = DateTime.now
  end

  # GET /events/1/edit
  def edit
    enforce_ownership(@event)
  end

  # GET /events/1/invite
  def invite
    enforce_visibility(@event)
    @invite = Invite.new
  end

  # POST /events/1/invite
  def send_invite
    enforce_visibility(@event)
    @invite = Invite.new(invite_params)
    @invite.event = @event
    @invite.user =  current_user
    @invite.deliver
    redirect_to event_path(@event), notice: "Invite sent"
  end

  # GET /events/1/join
  def join
    enforce_visibility(@event)
    user = User.find_by_id(params[:user_id]) || current_user
    enforce_ownership(user)
    user.join_event(@event)

    respond_to do |format|
      format.html { redirect_to return_url, notice: 'Event joined.' }
      format.js { render json: {} }
    end
  end

  # GET /events/1/leave
  def leave
    enforce_visibility(@event)
    user = User.find_by_id(params[:user_id]) || current_user
    enforce_ownership(user)
    user.leave_event(@event)

    respond_to do |format|
      format.html { redirect_to return_url, notice: 'Event left.' }
      format.js { render json: {} }
    end
  end

  def game_social_servers
    game_server = GameSocialServer.find(params[:game_social_server_id])
    enforce_ownership(game_server)
    enforce_visibility(@event)
    @event.game_social_servers.append(game_server) unless @event.game_social_servers.include? game_server
    redirect_to event_path(@event), notice: "Added #{game_server.name} to game servers"
  end

  def delete_game_social_server
    game_server = GameSocialServer.find(params[:game_social_server_id])
    enforce_ownership(game_server)
    enforce_visibility(@event)
    @event.game_social_servers.delete(game_server) if @event.game_social_servers.include? game_server
    redirect_to event_path(@event), notice: "Removed #{game_server.name} from game servers"
  end

  def return_url
    request.referrer || events_path
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user unless @event.user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    enforce_ownership(@event)
    respond_to do |format|
      if @event.update(event_params)
        @event.notify
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    enforce_ownership(@event)
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, 
                                    :description, 
                                    :start_time, 
                                    :end_time, 
                                    :user_id, 
                                    :location,
                                    :image_url,
                                    object_permission_attributes: [:permission_type])
    end

    def invite_params
      params.require(:invite).permit(:email)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:role => "form-horizontal"}) do |f| %>
  <% @event.set_defaults %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "help-inline" %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => "help-inline"  %><br>
    <%= f.text_area :description, :class => "form-control", :rows => "5" %>
  </div>

  <div class="form-group">
    <%= f.label :Image, :class => "help-inline"  %><br>
    <%= f.text_field :image_url, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :start_time, :class => "help-inline" %><br>
    <%= f.text_field(:start_time, :value=> @event.start_time.strftime('%Y-%m-%d %H:%M'), :class => "datetimepicker form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :end_time, :class => "help-inline" %><br>
    <%= f.text_field(:end_time, :value=> @event.end_time.strftime('%Y-%m-%d %H:%M'), :class => "datetimepicker form-control") %>
  </div>

  <div class="form-group">
    <%= f.fields_for :object_permission do |builder| %>
      <%= builder.label :type, "Visibility", :class => "help-inline" %><br>
      <%= builder.select :permission_type, ObjectPermission.event_permission_types(current_user), 
      {:selected => f.object.object_permission.permission_type}, 
      {:class => "form-control"} %>
  <% end %>
  </div>

  <% if is_admin? %>
    <div class="form-group">
      <%= f.label :user_id, :class => "help-inline" %><br>
      <%=  f.collection_select :user_id, User.all, :id, :name,  {:selected => (@event.user_id || current_user.id)}, {:class => "form-control"} %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :location, :class => "help-inline" %><br>
    <%= f.text_field :location, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/events/_invite_form.html.erb
<div class="modal" id="inviteModal">
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Invite User</h4>
        </div>
        <%= form_for(@invite, :url => url, :html => {:class => "form-horizontal"}) do |f| %>

        <div class="modal-body">
          <p>To invite someone to this <%= type %>, fill out their username or email in the following form</p>

          <div class="input">
            <%= f.label :user, :class => "help-inline" %><br>
            <%= f.autocomplete_field :email, autocomplete_user_name_users_path, :append_to => "#inviteModal" %>
          </div>
          <% if type == "Event" && current_user  %>
          <% friend_list =  current_user.friends.select {|f| f.games.include? game } %>
          <% if friend_list.size > 0 %>
          <div class="modal-body">
            <p>These are your friends who play <%= game.name %></p>
            <div class="row">
                <%  friend_list.each do |u| %>
                  <%= render "users/user", :u => u %>
                <% end %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
        <% if current_user %>
            <a href="#" data-dismiss="modal" class="btn">Close</a>
            <%= f.submit "Invite", :class => "btn btn-success" %>
        <% else %>
          <p>Sign in to invite</p>
        <% end %>
        </div>
        
        <% end %>
      </div>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Editing LAN Party</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, :class => "btn btn-warning" %>

app/views/events/index.html.erb
<div class="page-header">
  <h3 class="text-center h3-1-0">LAN Parties</h3>
  <%= link_to new_event_path, :class => "btn btn-success btn-left" do %>
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Create
  <% end %>
</div>

<%= grid(@events_grid) do |g|

  g.blank_slate  do
    content_tag :div, "No LAN Parties found", class: 'well'
  end

  g.row_attributes do |object|
    { onclick: "maybeVisit(event, '#{url_for(object)}');" }
  end

  g.column name: 'Name', attribute: 'name' do |event|
    event.name 
  end
  
  g.column name: 'Start Time', attribute: 'start_time' do |event|
    event.formatted_start_time 
  end
  
  g.column name: 'End Time', attribute: 'end_time' do |event|
    event.formatted_end_time
  end
  
  g.column name: 'Owner', model: User, attribute: 'name' do |event|
    event.user_name
  end
  
  g.column name: 'Location', attribute: 'location' do |event|
    event.location 
  end
  
  g.column do |event|
    if current_user
      render "users/attend", :attending => current_user.attending_event?(event), :join => join_event_path(event), :leave =>  leave_event_path(event), :id => event.id
    end
  end

  g.column do |event|
    if current_user && current_user.owns(event)
      link_to event, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do
        raw '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Destroy'
      end
    end
  end
end -%>

app/views/events/invite.html.erb
<h1>Send Invite</h1>

<%= render 'invite_form', :type => "LAN Party", :url => invite_event_path(@event) %>

<%= link_to 'Back', event_path(@event) %>

app/views/events/new.html.erb
<h1>Create Lan Party</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, :class => "btn btn-warning" %>

app/views/events/show.html.erb
<div class="page-header">
  <%= link_to events_path, :class => "btn btn-warning btn-left" do %>
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back
  <% end %>
  <%= render "users/attend", :attending => (current_user && current_user.attending_event?(@event)), :join => join_event_path(@event), :leave =>  leave_event_path(@event), :id => @event.id %>
  <%= link_to calendar_path(event_path(@event)), :class => "btn btn-primary btn-right" do %>
    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> ICal
  <% end %>
  <a data-toggle="modal" href="#inviteModal" class="btn btn-primary btn-right"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Invite</a>
  <h3 class="text-center"><%= @event.name %></h3>
</div>

<p id="notice"><%= notice %></p>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  <li role="presentation"><a href="#events" aria-controls="events" role="tab" data-toggle="tab">Events</a></li>
  <li role="presentation"><a href="#calendar-div" aria-controls="calendar-div" role="tab" data-toggle="tab">Calendar</a></li>
  <li role="presentation"><a href="#tournaments" aria-controls="tournaments" role="tab" data-toggle="tab">Tournaments</a></li>  
  <li role="presentation"><a href="#users" aria-controls="users" role="tab" data-toggle="tab">Attendees</a></li>  
  <li role="presentation"><a href="#game_servers" aria-controls="game_servers" role="tab" data-toggle="tab">Game Servers</a></li>  
  <li role="presentation"><a href="#games" aria-controls="games" role="tab" data-toggle="tab">Games</a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="info">
    <div class="panel panel-default">
      <div class="panel-heading">Summary</div>
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <%= image_tag @event.image_url, size: "200", class: "media-object" %>
          </div>
          <div class="media-body">
            <p><%= @event.description %></p>
          </div>
        </div>
      </div>

      <ul class="list-group">
        <li class="list-group-item">Start time: <%= @event.formatted_start_time %></li>
        <li class="list-group-item">End time: <%= @event.formatted_end_time %></li>
        <li class="list-group-item">Location: <%= @event.location %></li>
        <li class="list-group-item">Owner: <%= @event.user_name %></li>
        <li class="list-group-item">Visibility: <%= @event.object_permission.permission_type %></li>
        <% if current_user && current_user.owns(@event) %>
          <li class="list-group-item"><%= link_to edit_event_path(@event), :class => "btn btn-success" do %>
            <span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
          <% end %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="calendar-div">
    <div id="calendar"></div>
  <script type='text/javascript'>
      $(document).ready(function() {
      events =  [
        <% @event.game_events.each_with_index do |ge, i| %>
          {
            title  : '<%= ge.title %>',
            start  : '<%= ge.start_time %>',
            end    : '<%= ge.end_time %>'
          }<%= "," unless @event.tournaments.size == 0 %>
        <% end %>
        <% @event.tournaments.each_with_index do |t, i| %>
          {
            title  : '<%= t.name %>',
            start  : '<%= t.start_time %>',
            end    : '<%= t.end_time %>'
          }<%= "," unless i == @event.tournaments.size - 1 %>
        <% end %>
      ];
      start_time = "<%= @event.next_event.try(:game_start_time) || DateTime.now %>"
      create_calendar("#calendar", events, "agendaDay", start_time);
    });
    </script>
  </div>

  <div role="tabpanel" class="tab-pane" id="events">
    <div class="section-header">
      <% if @filter == "owned" %>
        <%= link_to event_path(@event), :class => "btn btn-success" do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Show All
        <% end %>
      <% else %>
       <%= link_to "#{event_path(@event)}/?filter=owned", :class => "btn btn-success" do %>
         <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Show Joinable
       <% end %>
      <% end %>
      <%= link_to new_game_event_for_event_path(@event), :class => "btn btn-success btn-right" do %>
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Create Event
      <% end %>
      <h2>Events</h2>
    </div>
    <%= render "game_events/game_events" %>
  </div>

  <div role="tabpanel" class="tab-pane" id="tournaments">
    <div class="section-header">
      <% if @filter_tournaments == "owned" %>
        <%= link_to event_path(@event), :class => "btn btn-success" do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Show All
        <% end %>
      <% else %>
        <%= link_to "#{event_path(@event)}/?filter_tournaments=owned", :class => "btn btn-success" do %>
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Show Joinable
        <% end %>
      <% end %>
      <%= link_to new_tournament_for_event_path(@event), :class => "btn btn-success btn-right" do %>
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Create Tournament
      <% end %>
      <h2>Tournaments</h2>
    </div>
    <%= render "tournaments/tournaments" %>
  </div>

  <div role="tabpanel" class="tab-pane" id="users">
    <div class="section-header section-header-centered">
      <h2>Attending</h2>
    </div>

    <% if @event.users.size > 0 %>
      <div class="row">
        <% for i in 0..3 %>
          <div class="col-lg-3 col-md-3">
            <%  @event.users.each_with_index do |u, index| %>
              <% if index % 4 == i %>
                <%= render "users/user", :u => u %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <h2>No Users Attending</h2>
    <% end %>
  </div>

  <div role="tabpanel" class="tab-pane" id="games">
    <div class="section-header section-header-centered">
      <h2>Games being played</h2>
    </div>
    <% @event.popular_games.each do |game_listing| %>

      <div role="tabpanel" class="tab-pane active" id="info">
        <div class="panel panel-default">
          <div class="panel-heading"><%= game_listing[:game].name %></div>
          <div class="panel-body">
            <div class="media">
              <div class="media-left">
                <%= image_tag game_listing[:game].logo_url, size: "200", class: "media-object" %>
              </div>
            </div>
          </div>

          <ul class="list-group">
            <%  game_listing[:users].each do |u| %>
            <li class="list-group-item"><%= render "users/user", :u => u %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>


    <% if current_user && current_user.attending_event?(@event) %>
      <p class="text-center"><a data-toggle="modal" href="#playlistModal" class="btn btn-primary">
      <span class="glyphicon glyphicon-list" aria-hidden="true"></span> 
      Manage Playlist</a></p>
    <% end %>
  </div>

  <div role="tabpanel" class="tab-pane" id="game_servers">
    <div class="section-header section-header-centered">
      <h2>Game Servers</h2>
    </div>
    <%= render "game_social_servers/game_social_servers" %>
  </div>
</div>

<div class="share-panel">
<p>Share this Lan Party:</p>
<%= social_share_button_tag(@event.name, url: event_url(@event), desc: @event.description, popup: "true", via: "gamesocialapp") %>
</div>

<% if current_user %>
  <h2>Comments</h2>
  <%= render "posts/posts", :object => @event %>
  <a data-toggle="modal" href="#postModal" class="btn btn-primary"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Post a Comment</a><br><br>
<% end %>
</div>

<%= render '/events/invite_form', :type => "LAN Party", :url => invite_event_path(@event) %>

<% if current_user %>
<%= render '/games/playlist_form', :playlist => current_user.playlist_for(@event) %>
<% end %>
<%= render '/posts/post_form', :type => "LAN Party", :url => posts_path %>

<script type='text/javascript'>
$(document).ready(function () {
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        $('#calendar').fullCalendar('render');
    });
    $('#myTab a:first').tab('show');
});
</script>