config/routes.rb
require 'sidekiq/web'

GameSocial::Application.routes.draw do
  match 'teams/:id/invite', to: 'teams#invite', as: 'invite_team', via: [:get]
  match 'teams/:id/invite', to: 'teams#send_invite', as: 'send_invite_team', via: [:post]
  match 'teams/new_for_tournament/:tournament_id', to: 'teams#new_for_tournament', as: 'new_team_for_tournament', via: [:get] 
  match 'teams/:id/join', to: 'teams#join', as: 'join_team', via: [:get]
  match 'teams/:id/leave', to: 'teams#leave', as: 'leave_team', via: [:get]
  resources :teams
  match 'tournaments/:id/rounds/:bracket_id/concede', to: 'tournaments#concede', as: 'concede_tournament_round', via: [:get] 
  match 'tournaments/:id/rounds/:bracket_id/resolve', to: 'tournaments#resolve', as: 'resolve_tournament_round', via: [:post] 
  match 'tournaments/:id/lock', to: 'tournaments#lock', as: 'lock_tournament', via: [:get] 
  match 'tournaments/new_for_event/:event_id', to: 'tournaments#new_for_event', as: 'new_tournament_for_event', via: [:get] 
  resources :tournaments

  match 'playlists/:id', to: 'playlists#add_game', as: 'add_game', via: [:post]
  match 'playlists/:id/:game_id', to: 'playlists#delete_game', as: 'delete_game', via: [:delete]
  resources :playlists

  match 'groups/:id/join', to: 'groups#join', as: 'join_group', via: [:get]
  match 'groups/:id/join/:user_id', to: 'groups#join', as: 'join_user_group', via: [:get]
  match 'groups/:id/leave', to: 'groups#leave', as: 'leave_group', via: [:get]
  match 'groups/:id/leave/:user_id', to: 'groups#leave', as: 'leave_user_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#invite', as: 'invite_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#send_invite', as: 'send_invite_group', via: [:post]
  resources :groups

  resources :posts

  match 'game_events/new_for_event/:event_id', to: 'game_events#new_for_event', as: 'new_game_event_for_event', via: [:get] 
  match 'posts/new_for_event/:event_id', to: 'posts#new_for_event', as: 'new_post_for_event', via: [:get] 
  match 'posts/new_for_game_event/:game_event_id', to: 'posts#new_for_game_event', as: 'new_post_for_game_event', via: [:get] 
  match 'game_events/:id/join', to: 'game_events#join', as: 'join_game_event', via: [:get]
  match 'game_events/:id/join/:user_id', to: 'game_events#join', as: 'join_user_game_event', via: [:get]
  match 'game_events/:id/leave', to: 'game_events#leave', as: 'leave_game_event', via: [:get]
  match 'game_events/:id/leave/:user_id', to: 'game_events#leave', as: 'leave_user_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#invite', as: 'invite_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#send_invite', as: 'send_invite_game_event', via: [:post]
  resources :game_events

  match 'events/:id/game_social_servers', to: 'events#game_social_servers', as: 'events_game_social_servers', via: [:post]
  match 'events/:id/game_social_servers/:game_social_server_id', to: 'events#delete_game_social_server', as: 'delete_events_game_social_server', via: [:delete]
  match 'events/:id/join', to: 'events#join', as: 'join_event', via: [:get]
  match 'events/:id/join/:user_id', to: 'events#join', as: 'join_user_event', via: [:get]
  match 'events/:id/leave', to: 'events#leave', as: 'leave_event', via: [:get]
  match 'events/:id/leave/:user_id', to: 'events#leave', as: 'leave_user_event', via: [:get]
  match 'events/:id/invite', to: 'events#invite', as: 'invite_event', via: [:get]
  match 'events/:id/invite', to: 'events#send_invite', as: 'send_invite_event', via: [:post]
  resources :events

  resources :alerts

  resources :alert_conditions

  resources :alert_schedules

  resources :game_locations

  resources :friendships

  match 'game_social_servers/new_source', to: 'game_social_servers#new_source', as: 'new_source_game_social_server', via: [:get]
  resources :game_social_servers

  resources :chat_servers

  match 'users/sync', to: 'users#sync', as: 'sync_users', via:[:get]
  match 'users/sync_location', to: 'users#sync_location', as: 'sync_users_location', via:[:get]
  match 'users/:id/games', to: 'users#add_game', as: 'user_game', via: [:post]
  resources :users do
    get :autocomplete_user_name, :on => :collection
  end
  resources :users

  resources :games
  root to: 'users#home'
  match 'auth/steam/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/developer/callback', to: 'sessions#create', via: [:get, :post]
 
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end unless Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  delegate :name, :to => :friend, :prefix => true, :allow_nil => true
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_login
  before_filter :enforce_admin, only: [:index]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all.paginate(:page => params[:page])
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    #@friendship = Friendship.new(friendship_params)
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friendship }
      else
        format.html { render action: 'new' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
      enforce_ownership(@friendship)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<%= will_paginate @friendships %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @friendships %>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>