config/routes.rb
require 'sidekiq/web'

GameSocial::Application.routes.draw do
  match 'teams/:id/invite', to: 'teams#invite', as: 'invite_team', via: [:get]
  match 'teams/:id/invite', to: 'teams#send_invite', as: 'send_invite_team', via: [:post]
  match 'teams/new_for_tournament/:tournament_id', to: 'teams#new_for_tournament', as: 'new_team_for_tournament', via: [:get] 
  match 'teams/:id/join', to: 'teams#join', as: 'join_team', via: [:get]
  match 'teams/:id/leave', to: 'teams#leave', as: 'leave_team', via: [:get]
  resources :teams
  match 'tournaments/:id/rounds/:bracket_id/concede', to: 'tournaments#concede', as: 'concede_tournament_round', via: [:get] 
  match 'tournaments/:id/rounds/:bracket_id/resolve', to: 'tournaments#resolve', as: 'resolve_tournament_round', via: [:post] 
  match 'tournaments/:id/lock', to: 'tournaments#lock', as: 'lock_tournament', via: [:get] 
  match 'tournaments/new_for_event/:event_id', to: 'tournaments#new_for_event', as: 'new_tournament_for_event', via: [:get] 
  resources :tournaments

  match 'playlists/:id', to: 'playlists#add_game', as: 'add_game', via: [:post]
  match 'playlists/:id/:game_id', to: 'playlists#delete_game', as: 'delete_game', via: [:delete]
  resources :playlists

  match 'groups/:id/join', to: 'groups#join', as: 'join_group', via: [:get]
  match 'groups/:id/join/:user_id', to: 'groups#join', as: 'join_user_group', via: [:get]
  match 'groups/:id/leave', to: 'groups#leave', as: 'leave_group', via: [:get]
  match 'groups/:id/leave/:user_id', to: 'groups#leave', as: 'leave_user_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#invite', as: 'invite_group', via: [:get]
  match 'groups/:id/invite', to: 'groups#send_invite', as: 'send_invite_group', via: [:post]
  resources :groups

  resources :posts

  match 'game_events/new_for_event/:event_id', to: 'game_events#new_for_event', as: 'new_game_event_for_event', via: [:get] 
  match 'posts/new_for_event/:event_id', to: 'posts#new_for_event', as: 'new_post_for_event', via: [:get] 
  match 'posts/new_for_game_event/:game_event_id', to: 'posts#new_for_game_event', as: 'new_post_for_game_event', via: [:get] 
  match 'game_events/:id/join', to: 'game_events#join', as: 'join_game_event', via: [:get]
  match 'game_events/:id/join/:user_id', to: 'game_events#join', as: 'join_user_game_event', via: [:get]
  match 'game_events/:id/leave', to: 'game_events#leave', as: 'leave_game_event', via: [:get]
  match 'game_events/:id/leave/:user_id', to: 'game_events#leave', as: 'leave_user_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#invite', as: 'invite_game_event', via: [:get]
  match 'game_events/:id/invite', to: 'game_events#send_invite', as: 'send_invite_game_event', via: [:post]
  resources :game_events

  match 'events/:id/game_social_servers', to: 'events#game_social_servers', as: 'events_game_social_servers', via: [:post]
  match 'events/:id/game_social_servers/:game_social_server_id', to: 'events#delete_game_social_server', as: 'delete_events_game_social_server', via: [:delete]
  match 'events/:id/join', to: 'events#join', as: 'join_event', via: [:get]
  match 'events/:id/join/:user_id', to: 'events#join', as: 'join_user_event', via: [:get]
  match 'events/:id/leave', to: 'events#leave', as: 'leave_event', via: [:get]
  match 'events/:id/leave/:user_id', to: 'events#leave', as: 'leave_user_event', via: [:get]
  match 'events/:id/invite', to: 'events#invite', as: 'invite_event', via: [:get]
  match 'events/:id/invite', to: 'events#send_invite', as: 'send_invite_event', via: [:post]
  resources :events

  resources :alerts

  resources :alert_conditions

  resources :alert_schedules

  resources :game_locations

  resources :friendships

  match 'game_social_servers/new_source', to: 'game_social_servers#new_source', as: 'new_source_game_social_server', via: [:get]
  resources :game_social_servers

  resources :chat_servers

  match 'users/sync', to: 'users#sync', as: 'sync_users', via:[:get]
  match 'users/sync_location', to: 'users#sync_location', as: 'sync_users_location', via:[:get]
  match 'users/:id/games', to: 'users#add_game', as: 'user_game', via: [:post]
  resources :users do
    get :autocomplete_user_name, :on => :collection
  end
  resources :users

  resources :games
  root to: 'users#home'
  match 'auth/steam/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/google_oauth2/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/developer/callback', to: 'sessions#create', via: [:get, :post]
 
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end unless Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
end

app/models/alert.rb
require 'workers/alert_worker'
class Alert < ActiveRecord::Base
  belongs_to :alert_schedule
  delegate :user, :to => :alert_schedule, :allow_nil => true
  delegate :name, :to => :alert_schedule, :prefix => true, :allow_nil => true
  delegate :game_name, :to => :payload, :allow_nil => true
  delegate :user_name, :to => :payload, :allow_nil => true
  serialize :payload

  after_create :deliver_alert

  def delivered?
    delivered_at.present?
  end

  def deliver_alert
    user.notify_websocket(self)
    Workers::AlertWorker.perform_async(id)
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_login
  before_filter :enforce_admin, except: [:show]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts_grid = initialize_grid(all_owned(Alert), :include => [:alert_schedule])
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @alert }
      else
        format.html { render action: 'new' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
      enforce_ownership(@alert)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:alert_schedule_id, :payload, :title, :description)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alert_schedule_id %><br>
    <%= f.number_field :alert_schedule_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1 class="text-center">Alerts</h1>

<%= grid(@alerts_grid) do |g|

  g.blank_slate  do
    content_tag :div, "No Alerts found", class: 'well'
  end

  g.row_attributes do |object|
    { onclick: "maybeVisit(event, '#{url_for(object)}');" }
  end

  g.column name: 'Schedule', model: AlertSchedule, attribute: 'name' do |alert|
    alert.alert_schedule_name
  end

  g.column name: 'Name', attribute: 'title' do |alert|
    alert.title
end

  g.column name: 'Description', attribute: 'description' do |alert|
    alert.description
  end

  g.column do |alert|
    if current_user.is_admin?
      link_to 'Edit', edit_alert_path(alert), :class => "btn btn-primary"
    end
  end

  g.column do |alert|
    if current_user.owns(alert)
      link_to 'Destroy', alert, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }
    end
  end
end -%>

<%= link_to 'Create Alert', new_alert_path, :class => "btn btn-success" %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<div class="pagination-centered">

<p id="notice"><%= notice %></p>

<table class="table table-condensed">
  <tr>
    <td><h5 class="text-center">Alert Schedule</h5></td>
    <td><p class="text-center"><%= @alert.alert_schedule_name %></p></td>
  </tr>
  <tr>
    <td><h5 class="text-center">Title</h5></td>
    <td><p class="text-center"><%= @alert.title %></p></td>
  </tr>
  <tr>
    <td><h5 class="text-center">Description</h5></td>
    <td><p class="text-center"><%= @alert.description %></p></td>
  </tr>
</table>

<%= link_to 'Edit', edit_alert_path(@alert), :class => "btn btn-primary" %> 
<%= link_to 'Back', alerts_path, :class => "btn btn-warning" %>
</div>